language: node_js
node_js:
  - "4.2"
script: cd ui && npm install && npm run build && cd ..
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && cd ui && npm run deploy'
